### ISSUE TITLE
ErrorException [3] This is an Error

### ISSUE THREAD

**Issue by chadicus** [chadicus/sandbox#11]
#0 /home/chadicus/projects/sandbox/exception-tracker.php(15): doSomething()
#1 /home/chadicus/projects/sandbox/exception-tracker.php(20): goDo()
#2 /home/chadicus/projects/sandbox/exception-tracker.php(28): go()
#3 {main}

**Comment by chadicus** [comment]
Additional Occurance Fri, 18 Sep 2015 16:16:08 -0400

**Comment by chadicus** [comment]
Additional Occurance Fri, 18 Sep 2015 16:17:03 -0400
